#!/usr/bin/env python3
"""Validate Minecraft 1.21.4 data packs generated by Hermes agents."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path


EXPECTED_PACK_FORMAT = 61
VALID_NAMESPACE_RE = re.compile(r"^[a-z0-9_.-]+$")


def read_json(path: Path, issues: list[str]) -> object | None:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        issues.append(f"{path} is invalid JSON: {exc}")
    except OSError as exc:
        issues.append(f"{path} could not be read: {exc}")
    return None


def write_json(path: Path, data: object, fixes: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    fixes.append(f"updated {path}")


def validate_pack_mcmeta(project: Path, fix: bool, issues: list[str], fixes: list[str]) -> None:
    path = project / "pack.mcmeta"
    if not path.exists():
        issues.append(f"missing {path}")
        if fix:
            write_json(
                path,
                {"pack": {"pack_format": EXPECTED_PACK_FORMAT, "description": "Zion data pack"}},
                fixes,
            )
        return

    data = read_json(path, issues)
    if not isinstance(data, dict):
        return
    pack = data.setdefault("pack", {})
    if not isinstance(pack, dict):
        issues.append(f"{path} pack must be a JSON object")
        return

    current = pack.get("pack_format")
    if current != EXPECTED_PACK_FORMAT:
        issues.append(
            f"{path} pack_format should be {EXPECTED_PACK_FORMAT} for Minecraft 1.21.4, got {current}"
        )
        if fix:
            pack["pack_format"] = EXPECTED_PACK_FORMAT
            write_json(path, data, fixes)


def validate_namespaces(project: Path, issues: list[str]) -> None:
    data_root = project / "data"
    if not data_root.exists():
        issues.append(f"missing {data_root}")
        return

    namespaces = [path.name for path in data_root.iterdir() if path.is_dir()]
    if not namespaces:
        issues.append(f"{data_root} has no namespace folders")

    for namespace in namespaces:
        if not VALID_NAMESPACE_RE.match(namespace):
            issues.append(f"namespace {namespace!r} must be lowercase letters, digits, underscores, dots, or hyphens")


def validate_json_files(project: Path, issues: list[str]) -> None:
    for path in sorted((project / "data").rglob("*.json")):
        read_json(path, issues)


def validate_functions(project: Path, issues: list[str]) -> None:
    for path in sorted((project / "data").rglob("*.mcfunction")):
        for line_no, raw_line in enumerate(path.read_text(encoding="utf-8", errors="ignore").splitlines(), 1):
            line = raw_line.strip()
            if not line or line.startswith("#"):
                continue
            if line.startswith("/"):
                issues.append(f"{path}:{line_no} function commands must not start with '/'")


def validate(project: Path, fix: bool) -> tuple[list[str], list[str]]:
    project = project.resolve()
    issues: list[str] = []
    fixes: list[str] = []

    validate_pack_mcmeta(project, fix, issues, fixes)
    validate_namespaces(project, issues)
    validate_json_files(project, issues)
    validate_functions(project, issues)

    if fix and fixes:
        issues, fixes_after = validate(project, fix=False)
        fixes.extend(fixes_after)

    return issues, fixes


def main() -> int:
    parser = argparse.ArgumentParser(description="Validate Minecraft 1.21.4 data packs.")
    parser.add_argument("--project", default=".", help="Data pack root containing pack.mcmeta")
    parser.add_argument("--fix", action="store_true", help="repair pack.mcmeta pack_format when possible")
    args = parser.parse_args()

    issues, fixes = validate(Path(args.project), args.fix)
    for fix in fixes:
        print(f"FIXED: {fix}")

    if issues:
        for issue in issues:
            print(f"ISSUE: {issue}", file=sys.stderr)
        return 1

    print("Hermes data pack guard passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
